
global:
  smtp_smarthost: mail.leedarson.com:465
  smtp_from: 2b_send@leedarson.com
  smtp_require_tls: true
  smtp_auth_username: 2b_send@leedarson.com
  smtp_auth_password: enc1:2zFRN86SvEPy3EBVYYUIxprx4JFwWlhrv48jHQslc_G1VajiN3ID5lLa7mLAilTv5YPm1U76u9zb5rhkQ09ZqqqtH24ce-nhRkWcUQ

route:
  receiver: email
  group_by:
  - alertname
  - job
  - instance
  - gateway_id
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 24h

receivers:
- name: email
  email_configs:
  - to: 2b_support@leedarson.com
    send_resolved: true
